version: '3.8'

services:
  frontend:
    build:
      context: ./client/lingua-read-client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx)
    environment:
      - REACT_APP_API_URL=http://backend:8080 # Backend listens on 8080 inside the container network
    depends_on:
      - backend
    networks:
      - linguaread-net

  backend:
    build:
      context: . # Build context is the project root
      dockerfile: server/LinguaReadApi/Dockerfile
    ports:
      - "5000:8080" # Map host port 5000 to container port 8080 (ASP.NET Core)
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=linguaread_db;Username=linguaread_user;Password=linguaread_password
    depends_on:
      - db
    networks:
      - linguaread-net

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: linguaread_user
      POSTGRES_PASSWORD: linguaread_password
      POSTGRES_DB: linguaread_db
    volumes:
      - postgres-data:/var/lib/postgresql/data # Use a named volume for persistence
    ports: # Optional: Expose DB port to host for debugging/management
      - "5432:5432"
    networks:
      - linguaread-net

volumes:
  postgres-data: # Define the named volume

networks:
  linguaread-net:
    driver: bridge